// Generated by @mnemonica/tactica - DO NOT EDIT
// This file provides complete TypeScript interfaces for Mnemonica types

/* eslint-disable @typescript-eslint/no-empty-object-type */
/* eslint-disable @typescript-eslint/no-empty-interface */

import type { ProtoFlat } from 'mnemonica';

export type List = {
	items: Array<string>;
	currentIndex: number;
	Slide: new (data: { view: 'MDX' | 'Title' | 'Title2' | 'Starter'; data: string; settings?: Record<string, unknown>; title?: string; subtitle?: string; author?: string }) => List_Slide;
};

export type List_Slide = ProtoFlat<List, {
	view: string;
	data: string;
	settings: Record<string, unknown>;
	Slide: undefined;
}>;
